export interface Mentor {
  id: string
  name: string
  linkedin: string
  company: string
  category: 'founder' | 'growth' | 'professionals'
  avatar?: string
}

export const mentors: Mentor[] = [
  // FOUNDERS
  {
    id: 'f1',
    name: 'Arpan Garg',
    linkedin: 'https://www.linkedin.com/in/arpansac/',
    company: 'Commudle',
    category: 'founder',
  },
  {
    id: 'f2',
    name: 'Rohan Mishra',
    linkedin: 'https://www.linkedin.com/in/iamrohanmishra/',
    company: 'Arabica Design Studio',
    category: 'founder',
  },
  {
    id: 'f3',
    name: 'Shivangi Singh',
    linkedin: 'https://www.linkedin.com/in/shivi-singh/',
    company: 'MyCTO',
    category: 'founder',
  },
  {
    id: 'f4',
    name: 'Sneh Soni',
    linkedin: 'https://www.linkedin.com/in/sneh-soni-/',
    company: 'FreeStand',
    category: 'founder',
  },
  {
    id: 'f5',
    name: 'Piyush Katyayan',
    linkedin: 'https://www.linkedin.com/in/piyushrajk/',
    company: 'Piyush Academy',
    category: 'founder',
  },
  {
    id: 'f6',
    name: 'Vineet Chirania',
    linkedin: 'https://www.linkedin.com/in/vineet-chirania/',
    company: 'Trainman',
    category: 'founder',
  },
  {
    id: 'f7',
    name: 'Vijay Kant',
    linkedin: 'https://www.linkedin.com/in/vijaykantofficial/',
    company: 'Kabadhatao',
    category: 'founder',
  },
  {
    id: 'f8',
    name: 'Dolly Bhasin',
    linkedin: 'https://www.linkedin.com/in/dollybhasin/',
    company: 'Smartedge',
    category: 'founder',
  },

  // GROWTH
  {
    id: 'g1',
    name: 'Aditya Singh',
    linkedin: 'https://www.linkedin.com/in/aditya-singh-emitop/',
    company: 'Road to Grow',
    category: 'growth',
  },
  {
    id: 'g2',
    name: 'Megha Sharma',
    linkedin: 'https://www.linkedin.com/in/meghanify/',
    company: 'Growthfueler',
    category: 'growth',
  },
  {
    id: 'g3',
    name: 'Ananya Narang',
    linkedin: 'https://www.linkedin.com/in/ananya-narang/',
    company: 'Entourage',
    category: 'growth',
  },
  {
    id: 'g4',
    name: 'Samridhi Bhardwaj',
    linkedin: 'https://www.linkedin.com/in/samridhi-bhardwaj-sb/',
    company: 'Uniquirk',
    category: 'growth',
  },
  {
    id: 'g5',
    name: 'Vanshika Mehta',
    linkedin: 'https://www.linkedin.com/in/vanshikamehta/',
    company: 'The Fingerprint Labs',
    category: 'growth',
  },
  {
    id: 'g6',
    name: 'Riya Tiwari',
    linkedin: 'https://www.linkedin.com/in/riyatiwari-personalbrandingstrategist/',
    company: 'Personal Branding Strategist',
    category: 'growth',
  },

  // PROFESSIONALS
  {
    id: 'p1',
    name: 'Singdha Kashyap',
    linkedin: 'https://www.linkedin.com/in/snigdha-kashyap-6825211b9/',
    company: 'Expedia Group',
    category: 'professionals',
  },
  {
    id: 'p2',
    name: 'Abhishek Shankhdhar',
    linkedin: 'https://www.linkedin.com/in/abhishekshankhdhar/',
    company: 'Deloitte',
    category: 'professionals',
  },
  {
    id: 'p3',
    name: 'Anand Gangadharan',
    linkedin: 'https://www.linkedin.com/in/anand-gangadharan/',
    company: 'American Express',
    category: 'professionals',
  },
  {
    id: 'p4',
    name: 'Tushar Debnath',
    linkedin: 'https://www.linkedin.com/in/tushardebnath/',
    company: 'Info Edge India Ltd',
    category: 'professionals',
  },
  {
    id: 'p5',
    name: 'Vineet Chirania',
    linkedin: 'https://www.linkedin.com/in/vineet-chirania/',
    company: 'Adani Digital Labs',
    category: 'professionals',
  },
  {
    id: 'p6',
    name: 'Shruti Raj',
    linkedin: 'https://www.linkedin.com/in/shruti-raj-5109001ba/',
    company: 'Factacy.ai',
    category: 'professionals',
  },
  {
    id: 'p7',
    name: 'Siddharth Arora',
    linkedin: 'https://www.linkedin.com/in/siddharth-arora-77021b17a/',
    company: 'UKG, Ex-Mobikwik',
    category: 'professionals',
  },
  {
    id: 'p8',
    name: 'Komal Kumar Singh',
    linkedin: 'https://www.linkedin.com/in/komal-kumar-singh-966651133/',
    company: 'Capgemini',
    category: 'professionals',
  },
  {
    id: 'p9',
    name: 'Kundan Kumar',
    linkedin: 'https://www.linkedin.com/in/9911552016/',
    company: 'Capgemini',
    category: 'professionals',
  },
  {
    id: 'p10',
    name: 'Mohit Singh',
    linkedin: 'https://www.linkedin.com/in/mohit3103/',
    company: 'Cradlewise',
    category: 'professionals',
  },
  {
    id: 'p11',
    name: 'Manan Bedi',
    linkedin: 'https://www.linkedin.com/in/manan-bedi2908/',
    company: 'Paytm',
    category: 'professionals',
  },
  {
    id: 'p12',
    name: 'Keshi Jain',
    linkedin: 'https://www.linkedin.com/in/keshi-jain-44b62a223/',
    company: 'Maruti Suzuki',
    category: 'professionals',
  },
  {
    id: 'p13',
    name: 'Palak Awasthi',
    linkedin: 'https://www.linkedin.com/in/palakawasthi/',
    company: 'PayPal',
    category: 'professionals',
  },
  {
    id: 'p14',
    name: 'Ragini Saini',
    linkedin: 'https://www.linkedin.com/in/ragini-saini-851933112/',
    company: 'Financial Express',
    category: 'professionals',
  },
  {
    id: 'p15',
    name: 'Loveleen Kaur',
    linkedin: 'https://www.linkedin.com/in/loveleen-kaur/',
    company: 'Astrotalk',
    category: 'professionals',
  },
  {
    id: 'p16',
    name: 'Abhishek Dubey',
    linkedin: 'https://www.linkedin.com/in/uxporte/',
    company: 'Tata Group',
    category: 'professionals',
  },
  {
    id: 'p17',
    name: 'Akhil Garg',
    linkedin: 'https://www.linkedin.com/in/akhilgarg1990/',
    company: 'EPAM',
    category: 'professionals',
  },
  {
    id: 'p18',
    name: 'Akhil Sukhnani',
    linkedin: 'https://www.linkedin.com/in/akhil-sukhnani/',
    company: 'Netskope',
    category: 'professionals',
  },
  {
    id: 'p19',
    name: 'Raghav Gupta',
    linkedin: 'https://www.linkedin.com/in/raghavcgartist/',
    company: 'Ex-Nagarro',
    category: 'professionals',
  },
  {
    id: 'p20',
    name: 'Kaustubha Shravan',
    linkedin: 'https://www.linkedin.com/in/kaustubhashravan/',
    company: 'Microsoft',
    category: 'professionals',
  },
  {
    id: 'p21',
    name: 'Shilpa Garg',
    linkedin: 'https://www.linkedin.com/in/shilpagarg13/',
    company: 'Deloitte',
    category: 'professionals',
  },
  {
    id: 'p22',
    name: 'Shruti Arora',
    linkedin: 'https://www.linkedin.com/in/shrutiiaroraaa/',
    company: 'Commudle',
    category: 'professionals',
  },
  {
    id: 'p23',
    name: 'Arun Soni',
    linkedin: 'https://www.linkedin.com/in/arunsoni8182/',
    company: 'Taylor & Francis Group',
    category: 'professionals',
  },
  {
    id: 'p24',
    name: 'Mohina Chadha',
    linkedin: 'https://www.linkedin.com/in/mohinachadha/',
    company: 'Times Internet',
    category: 'professionals',
  },
  {
    id: 'p25',
    name: 'Hitesh Lakhyani',
    linkedin: 'https://www.linkedin.com/in/hitesh-lakhyani-468b8a18/',
    company: 'Tata 1Mg',
    category: 'professionals',
  },
  {
    id: 'p26',
    name: 'Bhavna Singh',
    linkedin: 'https://www.linkedin.com/in/sbhavnas/',
    company: 'Signo',
    category: 'professionals',
  },
  {
    id: 'p27',
    name: 'Yug Sarin',
    linkedin: 'https://www.linkedin.com/in/yugsarin/',
    company: 'Airtel',
    category: 'professionals',
  },
  {
    id: 'p28',
    name: 'Arushi Garg',
    linkedin: 'https://www.linkedin.com/in/arushi-garg105/',
    company: 'Adobe',
    category: 'professionals',
  },
  {
    id: 'p29',
    name: 'Manvi Singhwal',
    linkedin: 'https://www.linkedin.com/in/manvisinghwal/',
    company: 'ClassCover',
    category: 'professionals',
  },
  {
    id: 'p30',
    name: 'Vishal Yagyasaini',
    linkedin: 'https://www.linkedin.com/in/vishal-yagyasaini-634841118',
    company: 'Industrial Designer | NIT Andhra',
    category: 'professionals',
  },
  {
    id: 'p31',
    name: 'Satendra Kumar',
    linkedin: 'https://www.linkedin.com/in/satendra17',
    company: 'Policybazaar',
    category: 'professionals',
  },
  {
    id: 'p32',
    name: 'Shakti Arora',
    linkedin: 'https://www.linkedin.com/in/shakti-arora-59536898',
    company: 'Lenskart',
    category: 'professionals',
  },
  {
    id: 'p33',
    name: 'Aryan Gupta',
    linkedin: 'https://www.linkedin.com/in/aryanux',
    company: 'Leap Wallet',
    category: 'professionals',
  },
  {
    id: 'p34',
    name: 'Swarnima Yagyasaini',
    linkedin: 'https://www.linkedin.com/in/swarnima-yagya-saini-588b68129',
    company: 'Payoneer',
    category: 'professionals',
  },
  {
    id: 'p35',
    name: 'Pragya Mishra',
    linkedin: 'https://www.linkedin.com/in/pragya-mishra-916112163',
    company: 'HARMAN International',
    category: 'professionals',
  },
  {
    id: 'p36',
    name: 'Muneer Khan',
    linkedin: 'https://www.linkedin.com/in/mk4el',
    company: 'Cadre Tech',
    category: 'professionals',
  },
  {
    id: 'p37',
    name: 'Alisha Shaw',
    linkedin: 'https://www.linkedin.com/in/alisha-shaw',
    company: 'ARC Document Solutions',
    category: 'professionals',
  },
  {
    id: 'p38',
    name: 'Raghav Awasthi',
    linkedin: 'https://www.linkedin.com/in/iamraghavawasthi',
    company: 'OLA',
    category: 'professionals',
  },
  {
    id: 'p39',
    name: 'Varun Bhanot',
    linkedin: 'https://www.linkedin.com/in/varunbhanot/',
    company: 'Deutsche Telekom Digital Labs',
    category: 'professionals',
  },
]

export const categories = [
  { value: 'all', label: 'All Mentors' },
  { value: 'founder', label: 'Founders' },
  { value: 'growth', label: 'Growth' },
  { value: 'professionals', label: 'Professionals' },
] as const

export type CategoryValue = typeof categories[number]['value']
