-- Insert Founders
INSERT INTO mentors (name, linkedin_url, brand_name, category) VALUES
('Arpan Gargh', 'https://www.linkedin.com/in/arpansac/', 'Commudle', 'Founders'),
('Rohan Mishra', 'https://www.linkedin.com/in/iamrohanmishra/', 'Arabica Design Studio', 'Founders'),
('Shivangi Singh', 'https://www.linkedin.com/in/shivi-singh/', 'MyCTO', 'Founders'),
('Sneh Soni', 'https://www.linkedin.com/in/sneh-soni-/', 'FreeStand', 'Founders'),
('Piyush Katyayan', 'https://www.linkedin.com/in/piyushrajk/', 'Piyush Academy', 'Founders'),
('Vineet Chirania', 'https://www.linkedin.com/in/vineet-chirania/', 'Trainman', 'Founders'),
('Vijay Kanth', 'https://www.linkedin.com/in/vijaykantofficial/', 'Kabadhato', 'Founders'),
('Dolly Bhasin', 'https://www.linkedin.com/in/dollybhasin/', 'Smartedge', 'Founders');

-- Insert Growth & Marketing
INSERT INTO mentors (name, linkedin_url, brand_name, category) VALUES
('Aditya Singh', 'https://www.linkedin.com/in/aditya-singh-emitop/', 'Road to Grow', 'Growth & Marketing'),
('Megha Sharma', 'https://www.linkedin.com/in/meghanify/', 'Growthfueler', 'Growth & Marketing'),
('Ananya Narang', 'https://www.linkedin.com/in/ananya-narang/', 'Entourage', 'Growth & Marketing'),
('Samridhi Bhardwaj', 'https://www.linkedin.com/in/samridhi-bhardwaj-sb/', 'Uniquirk', 'Growth & Marketing'),
('Vanshika Mehta', 'https://www.linkedin.com/in/vanshikamehta/', 'The Fingerprint Labs', 'Growth & Marketing'),
('Riya Tiwari', 'https://www.linkedin.com/in/riyatiwari-personalbrandingstrategist/', 'Personal Branding Strategist', 'Growth & Marketing');

-- Insert Professionals
INSERT INTO mentors (name, linkedin_url, brand_name, category) VALUES
('Singdha Kashyap', 'https://www.linkedin.com/in/snigdha-kashyap-6825211b9/', 'Expedia Group', 'Professionals'),
('Abhishek Shankhdhar', 'https://www.linkedin.com/in/abhishekshankhdhar/', 'Deloitte', 'Professionals'),
('Anand Gangadharan', 'https://www.linkedin.com/in/anand-gangadharan/', 'American Express', 'Professionals'),
('Tushar Debnath', 'https://www.linkedin.com/in/tushardebnath/', 'Info Edge India Ltd', 'Professionals'),
('Shruti Raj', 'https://www.linkedin.com/in/shruti-raj-5109001ba/', 'Factacy.ai', 'Professionals'),
('Siddharth Arora', 'https://www.linkedin.com/in/siddharth-arora-77021b17a/', 'UKG, Ex-Mobikwik', 'Professionals'),
('Komal Kumar Singh', 'https://www.linkedin.com/in/komal-kumar-singh-966651133/', 'Capgemini', 'Professionals'),
('Kundan Kumar', 'https://www.linkedin.com/in/9911552016/', 'Capgemini', 'Professionals'),
('Mohit Singh', 'https://www.linkedin.com/in/mohit3103/', 'Cradlewise', 'Professionals'),
('Manan Bedi', 'https://www.linkedin.com/in/manan-bedi2908/', 'Paytm', 'Professionals'),
('Keshi Jain', 'https://www.linkedin.com/in/keshi-jain-44b62a223/', 'Maruti Suzuki', 'Professionals'),
('Palak Awasthi', 'https://www.linkedin.com/in/palakawasthi/', 'Paypal', 'Professionals'),
('Ragini Saini', 'https://www.linkedin.com/in/ragini-saini-851933112/', 'Financial Express', 'Professionals'),
('Loveleen Kaur', 'https://www.linkedin.com/in/loveleen-kaur/', 'Astrotalk', 'Professionals'),
('Abhishek Dubey', 'https://www.linkedin.com/in/uxporte/', 'Tata Group', 'Professionals'),
('Akhil Garg', 'https://www.linkedin.com/in/akhilgarg1990/', 'EPAM', 'Professionals'),
('Akhil Sukhnani', 'https://www.linkedin.com/in/akhil-sukhnani/', 'Netskope', 'Professionals'),
('Raghav Gupta', 'https://www.linkedin.com/in/raghavcgartist/', 'Ex-Nagarro', 'Professionals'),
('Kaustubha Shravan', 'https://www.linkedin.com/in/kaustubhashravan/', 'Microsoft', 'Professionals'),
('Shilpa Garg', 'https://www.linkedin.com/in/shilpagarg13/', 'Deloitte', 'Professionals'),
('Shruti Arora', 'https://www.linkedin.com/in/shrutiiaroraaa/', 'Commudle', 'Professionals'),
('Arun Soni', 'https://www.linkedin.com/in/arunsoni8182/', 'Taylor & Francis Group', 'Professionals'),
('Mohina Chadha', 'https://www.linkedin.com/in/mohinachadha/', 'Times Internet', 'Professionals'),
('Hitesh Lakhyani', 'https://www.linkedin.com/in/hitesh-lakhyani-468b8a18/', 'Tata 1Mg', 'Professionals'),
('Bhavna Singh', 'https://www.linkedin.com/in/sbhavnas/', 'Signo', 'Professionals'),
('Yug Sarin', 'https://www.linkedin.com/in/yugsarin/', 'Airtel', 'Professionals'),
('Arushi Garg', 'https://www.linkedin.com/in/arushi-garg105/', 'Adobe', 'Professionals'),
('Manvi Singhwal', 'https://www.linkedin.com/in/manvisinghwal/', 'ClassCover', 'Professionals'),
('Vishal Yagyasaini', 'https://www.linkedin.com/in/vishal-yagyasaini-634841118', 'Industrial Designer | NIT Andhra', 'Professionals'),
('Satendra Kumar', 'https://www.linkedin.com/in/satendra17', 'Policybazaar', 'Professionals'),
('Shakti Arora', 'https://www.linkedin.com/in/shakti-arora-59536898', 'Lenskart', 'Professionals'),
('Aryan Gupta', 'https://www.linkedin.com/in/aryanux', 'Leap Wallet', 'Professionals'),
('Swarnima Yagyasaini', 'https://www.linkedin.com/in/swarnima-yagya-saini-588b68129', 'Payoneer', 'Professionals'),
('Pragya Mishra', 'https://www.linkedin.com/in/pragya-mishra-916112163', 'HARMAN International', 'Professionals'),
('Muneer Khan', 'https://www.linkedin.com/in/mk4el', 'Cadre Tech', 'Professionals'),
('Alisha Shaw', 'https://www.linkedin.com/in/alisha-shaw', 'ARC Document Solutions', 'Professionals'),
('Raghav Awasthi', 'https://www.linkedin.com/in/iamraghavawasthi', 'OLA', 'Professionals'),
('Varun Bhanot', 'https://www.linkedin.com/in/varunbhanot/', 'Deutsche Telekom Digital Labs', 'Professionals');
